[workspace]
authors = ["rensheng0410@outlook.com <rensheng0410@outlook.com>"]
channels = ["conda-forge"]
name = "td3bc_diffusion"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[feature.gpu.system-requirements]
cuda = "12.0"

[feature.gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "*"

[feature.cpu.dependencies]
pytorch-cpu = "*"

[environments]
cpu = ["cpu"]
default = ["gpu"]

[dependencies]
python = "3.12.*"
pettingzoo = "*"
gymnasium = "*"
rich = "*"

[pypi-dependencies]
mpe2 = "*"
stable_baselines3 = "*"
diffusers = "*"
